package com.flashtopia.indeedplainnote.alarmnotemodule;


import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;


class AlarmNoteDBOpenHelper extends SQLiteOpenHelper{

    private static final String DB_NAME = "alarm_notes.db";
    private static final int DATABASE_VERSION = 1;
    public static final String TABLE_ALARM_NOTES = "alarm_notes";
    public static final String COLUMN_ID ="alarmNoteId";//for id that will be generated by DB
    public static final String NOTE_ID ="noteId";//for id of note that executes note alarm
    public static final String COLUMN_TIME_SET = "alarmNoteTimeSet";
    public static final String COLUMN_ALERT_REQUEST_CODE = "alertRequestCode";

    public static final String COLUMN_NOTE ="alarmNote";

    private static final String TABLE_CREATE =
            "CREATE TABLE " + TABLE_ALARM_NOTES + " (" +
                    COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    NOTE_ID + " INTEGER, " +
                    COLUMN_TIME_SET + " INTEGER, " +
                    COLUMN_ALERT_REQUEST_CODE + " INTEGER, " +
                    COLUMN_NOTE + " TEXT " + ")";

    public static  final String[] ALL_COLUMNS ={

            COLUMN_ID,
            NOTE_ID,
            COLUMN_TIME_SET,
            COLUMN_ALERT_REQUEST_CODE,
            COLUMN_NOTE

    };


    public AlarmNoteDBOpenHelper(Context context) {

        super(context, DB_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {

        sqLiteDatabase.execSQL(TABLE_CREATE);
    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int oldVersion, int newVersion) {

        sqLiteDatabase.execSQL("DROP TABLE IF EXISTS "+TABLE_ALARM_NOTES);
        onCreate(sqLiteDatabase);

    }

}
